### ISSUE TITLE
6.3.0 - 2 Bindings Found that Match False Positive

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/Kodein-DI#216] opened 2019-06-20 18:14 UTC
I updated to 6.3.0 from 6.2.0 and I got this crash:

```
org.kodein.di.Kodein$NotFoundException: 2 bindings found that match bind<GlideListener<Drawable>>() with ?<MyActivity>().? { String -> ? }:
            module Media2 {
                bind<GlideListener<Drawable>>() with factory { String -> GlideListener<*> }
            }
            module Util {
                bind<DateFormat>() with factory { String -> SimpleDateFormat }
            }
```

They are bound as:

```
Bind<GlideListener<Drawable>>(generic()) with factory { name: String ->
    GlideListener<Drawable>(
        log = instance(arg = GlideListener.TAG),
        name = name
    )
  }
```

```
bind<DateFormat>() with factory { pattern: String ->
    SimpleDateFormat(pattern, Locale.getDefault())
  }
```

```
at org.kodein.di.internal.KodeinContainerImpl.factory(KodeinContainerImpl.kt:192)
        at org.kodein.di.KodeinContainer$DefaultImpls.factory$default(KodeinContainer.kt:33)
        at org.kodein.di.internal.DKodeinBaseImpl.Factory(DKodeinImpl.kt:18)
        at org.kodein.di.internal.BindingKodeinImpl.Factory(Unknown Source:12)
        at org.kodein.di.DKodeinBase$DefaultImpls.Factory$default(DKodein.kt:53)
        at com.myapp.di.modules.MediaKt$mediaModule$1$3.invoke(media.kt:58)
        at com.myapp.di.modules.MediaKt$mediaModule$1$3.invoke(Unknown Source:4)
        at org.kodein.di.bindings.Factory$getFactory$1.invoke(standardBindings.kt:20)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:32)
        at com.myapp.di.modules.AuthKt$authModule$1$5.invoke(auth.kt:119)
        at com.myapp.di.modules.AuthKt$authModule$1$5.invoke(Unknown Source:2)
        at org.kodein.di.bindings.Provider$getFactory$1.invoke(standardBindings.kt:88)
        at org.kodein.di.bindings.Provider$getFactory$1.invoke(standardBindings.kt:82)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
        at com.myapp.di.modules.UtilsKt$utilModule$1$21.invoke(utils.kt:536)
        at com.myapp.di.modules.UtilsKt$utilModule$1$21.invoke(Unknown Source:2)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.myapp.core.MyActivity.getPresenter(Unknown Source:7)
        at com.myapp.core.MyActivity.onCreate(MyActivity.kt:62)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        	... 11 more
```

**Comment by romainbsl** [comment] 2019-06-21 18:17
I'll take a look asap.

Do you have supplementary contextual information for me to be able to reproduce the error ?
It seems you're using modules right ?

**Comment by eygraber** [comment] 2019-06-21 18:25
None that I can think of off hand. I am using modules; any other info that would be helpful?

**Comment by romainbsl** [comment] 2019-06-21 18:56
I will provide a project samole to reproduce the issue. If I can't reproduce I'll come to you for more details

**Comment by romainbsl** [comment] 2019-06-22 08:56
I created a repo to try to reproduce the error, but without success
https://github.com/romainbsl/kodein-issue-216

- Is your project available for cloning and debug it ? 
- If not, if my sample project isn't right could you give me some details of what I'm missing ?

thx

**Comment by eygraber** [comment] 2019-06-24 18:39
It is not available for cloning and debugging. I will try to find the smallest portion of it that can repro this while still being shareable, but it will take time.

**Comment by jarmstrong** [comment] 2019-07-01 00:44
Have seen this issue since upgrading, in a test that overrides existing bindings with test bindings. Had a quick look inside and the test bindings appear to be added on top of the existing bindings instead of overriding them, which causes the `2 bindings found` issue as it can't pick at injection time. No code change, only the Gradle update.

**Comment by romainbsl** [comment] 2019-07-01 15:23
Thanks for the detail @jarmstrong , I reproduce the error, I will work on it.

**Comment by romainbsl** [comment] 2019-07-01 19:33
In fact, I managed to reproduce a case, but it also crash with `6.2`, so it might not be your case.

@eygraber how do you retrieve your bean ?

@jarmstrong what is your use case, how do you bind / retrieve your objects ?

**Comment by jarmstrong** [comment] 2019-07-02 01:07
It's a bit ugly but I have a global mutable kodein, which has a module injected when the app starts. In my instrumentation test, I then override these bindings in a new test module before test runs.

```
val testLoggingModule = Kodein.Module("test", true) {
                bind<IRepository<A>>() with singleton { MockARepository() }
                bind<IApi>() with singleton { MockApi() }
            }

kodein.addImport(testModule, allowOverride = true)
``` 

Let me know if I'm doing this wrong incase its user error.

Doing this runs in 6.2.1 but errors as above in 6.3.1

**Comment by eygraber** [comment] 2019-07-02 02:11
@romainbsl 

```
instance(arg="some string")
```

**Comment by romainbsl** [comment] 2019-07-02 04:03
@jarmstrong ok then, this means this isn't a **factory** issue. 
Do you use only **singleton** in your case or did your primary binding are something else ?
What are your false positive output ? Both **IRepository** and **IApi** ?

**Comment by jarmstrong** [comment] 2019-07-02 04:30
Only singleton in this case, the primary bindings are the same just with two different concrete classes.

```
org.kodein.di.Kodein$NotFoundException: 2 bindings found that match bind<IRepository<A>>() with ?<SomeKotlinParentObject>().? { ? }:
        module core {
            bind<Context>() with singleton { Context }
        }
        module testLogging {
            bind<IRepository<A>>() with singleton { MockARepository }
        }
Other bindings registered in Kodein:
        module testLogging {
            bind<IApi>() with singleton { MockApi }
        }
```

**Comment by ageevvalentin** [comment] 2019-07-09 14:16
I get the same crash after update from 6.2.0 to 6.3.2

Android Fragment binding:
```kotlin
bind<DataSource.Factory<Int, Message>>() with
    factory { organizationId: OrganizationId, filterParams: FilterParams ->
        RoomFactoryWrapper(
            MessageDataSourceFactory(
                provider(arg = M(organizationId, filterParams))
            )
        )
    }
bind<DataSource<Int, Message>>() with
    factory { organizationId: OrganizationId, filterParams: FilterParams ->
        MessageDataSource(instance(), instance(), organizationId, filterParams)
    }
```

Error:
```kotlin
2 bindings found that match bind<DataSource.Factory<Int, Message>>() with ?<ChatFragment>().? { Multi2<OrganizationId, FilterParams> -> ? }:
            module ChatModule {
                bind<DataSource.Factory<Int, Message>>() with factory { Multi2<OrganizationId, FilterParams> -> RoomFactoryWrapper<Message> }
                bind<DataSource<Int, Message>>() with factory { Multi2<OrganizationId, FilterParams> -> MessageDataSource }
            }
```

**Comment by romainbsl** [comment] 2019-07-11 10:56
Could you give a try with `6.3.3`, we found and fix a bug, but has we can't reproduce we can't check that it resolve this issue.

**Comment by eygraber** [comment] 2019-07-11 15:08
Looks like that fixed it for me.

**Comment by romainbsl** [comment] 2019-07-11 15:36
Cool. Sorry for the bug. I close the issue, feel free to reopen it if necessary

**Closed by romainbsl** 2019-07-11 15:36 UTC
Labels: type: bug

**Comment by jarmstrong** [comment] 2019-07-12 01:03
Looks like this has been resolved for me too
