### ISSUE TITLE
Unresolved reference when compiling with JS IR backend

### ISSUE THREAD

**Issue by lamba92** [Kodein-Framework/Kodein-DI#355] opened 2021-02-16 16:06 UTC
If importing `kodein-di` version `7.3.1` or `7.4.0-master-113` and targetting JS with new IR compilation backend, the compiler errors with `Unresolved reference: kodein`. 

The compiler do not find any reference to Kodein at all!

**Comment by romainbsl** [comment] 2021-02-16 19:34
It seems that others don't have this issue. What is you Gradle configuration?

**Comment by lamba92** [comment] 2021-02-16 19:47
The project is [kotlingram](https://github.com/lamba92/kotlingram), it uses Kodein in subproject `:api:bot-builder`.

Gradle build files:
- `:api:bot-builder` [build.gradle.kts](https://github.com/lamba92/kotlingram/blob/master/api/bot-builder/build.gradle.kts)
- `:api:core` [build.gradle.kts](https://github.com/lamba92/kotlingram/blob/master/api/core/build.gradle.kts)
- base plugin: [`KotlingramPublishedApiPlugin`](https://github.com/lamba92/kotlingram/blob/master/buildSrc/src/main/kotlin/com/github/lamba92/kotlingram/gradle/KotlingramPlugin.kt)

Gradle version 6.8.2
Kotlin version: 1.4.30
OS: Windows 10 x64 (also WSL Ubuntu 20.04)
JDK: AdoptOpenJDK 1.8 HotSpot

**Comment by romainbsl** [comment] 2021-02-17 13:59
I reproduced the issue on my first attempt to run the task `:api:bot-builder:compileKotlinJs` inside IDEA.
After that I removed my gradle caches, and was not able to reproduce, even after re-cloning the repo...

Here my console logs (on macos, but it doesn't matter for Kotlin/JS):
```shell
[14:54:12] ~/workspace/sandbox/kotlingram master✘
 $ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
 
[14:54:14] ~/workspace/sandbox/kotlingram master✘
 $ ./gradlew clean

> Configure project :generator
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.30`.

> Task :buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.8.2/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
w: /Users/romain/workspace/sandbox/kotlingram/buildSrc/src/main/kotlin/com/github/lamba92/kotlingram/gradle/tasks/GenerateWebpackConfig.kt: (96, 25): 'appendln(String?): kotlin.text.StringBuilder /* = java.lang.StringBuilder */' is deprecated. Use appendLine instead. Note that the new method always appends the line feed character '\n' regardless of the system line separator.
w: /Users/romain/workspace/sandbox/kotlingram/buildSrc/src/main/kotlin/com/github/lamba92/kotlingram/gradle/tasks/GenerateWebpackConfig.kt: (108, 25): 'appendln(String?): kotlin.text.StringBuilder /* = java.lang.StringBuilder */' is deprecated. Use appendLine instead. Note that the new method always appends the line feed character '\n' regardless of the system line separator.

> Task :generator:compileKotlin
The `kotlin-dsl` plugin applied to project ':generator' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.8.2/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
10 actionable tasks: 3 executed, 7 up-to-date
 
[14:54:35] ~/workspace/sandbox/kotlingram master✘
 $ ./gradlew :api:bot-builder:compileKotlinJs

> Configure project :generator
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.30`.

> Task :rootPackageJson
There are multiple versions of "kotlin" used in nodejs build: 1.4.21, 1.4.30. Only latest version will be used.

> Task :kotlinNpmInstall
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-client-json-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-client-core-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-http-cio-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-http-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-utils-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-io-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2af360b3-faa3-454d-91b0-7c21f351dc84 > kotlingram-bot-builder > ktor-ktor-client-serialization-jsLegacy > text-encoding@0.7.0: no longer maintained

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 18s
11 actionable tasks: 9 executed, 2 up-to-date
```

NB: My master is marked as desynchronised  because I had to make `./gradlew` executable

**Comment by lamba92** [comment] 2021-02-17 14:05
By "clearing Gradle caches" you mean `./gradlew clean`?

**Comment by romainbsl** [comment] 2021-02-17 14:18
nope, I meant removing my ~/.gradle/caches directory.

There is no message about missing Kodein-DI references in you gradle scan:
https://scans.gradle.com/s/xk3ws6ic36tye/console-log?task=:api:core:compileKotlinJsIr

**Comment by romainbsl** [comment] 2021-02-17 14:19
But I also reproduce the issue locally:
```shell
[15:17:26] ~/workspace/sandbox/kotlingram dev✘
 $ gw clean :api:bot-builder:compileKotlinJsIr    

> Configure project :generator
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.30`.

> Task :api:core:jsIrPackageJson
Cannot find build/js/packages_imported/kotlin/1.4.21, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-serialization-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-json-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-core-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-http-cio-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-http-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-utils-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-io-jsIr/1.5.1, rebuilding
Cannot find build/js/packages_imported/kotlin-test-js-runner/1.4.20, rebuilding
Cannot find build/js/packages_imported/kotlin-test/1.4.20, rebuilding

> Task :api:core:jsLegacyPackageJson
Cannot find build/js/packages_imported/kotlinx-serialization-kotlinx-serialization-json-jsLegacy/1.0.1, rebuilding
Cannot find build/js/packages_imported/kotlinx-serialization-kotlinx-serialization-core-jsLegacy/1.0.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-serialization-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-json-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-client-core-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-http-cio-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-http-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-utils-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/ktor-ktor-io-jsLegacy/1.5.1, rebuilding
Cannot find build/js/packages_imported/kotlinx-coroutines-core/1.4.2-native-mt, rebuilding
Cannot find build/js/packages_imported/kotlinx-atomicfu/0.14.4, rebuilding

> Task :api:bot-builder:jsIrPackageJson
Cannot find build/js/packages_imported/kotlin/1.4.30, rebuilding

> Task :rootPackageJson
There are multiple versions of "kotlin" used in nodejs build: 1.4.21, 1.4.30. Only latest version will be used.

> Task :kotlinNpmInstall
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-client-serialization-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-client-json-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-http-cio-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-http-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-utils-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-client-core-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-bot-builder-jsIr > ktor-ktor-io-jsIr > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-client-json-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-client-core-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-client-serialization-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-http-cio-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-io-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-utils-jsLegacy > text-encoding@0.7.0: no longer maintained
warning workspace-aggregator-2dd1c29b-66c1-48b7-b1a3-a3fc219dc574 > kotlingram-core-jsLegacy > ktor-ktor-http-jsLegacy > text-encoding@0.7.0: no longer maintained

> Task :api:core:compileKotlinJsIr FAILED
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (3, 38): Unresolved reference: api
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (10, 71): Unresolved reference: InlineQueryResult
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (10, 90): Unresolved reference: InlineQueryResult
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (12, 88): Unresolved reference: InlineQueryResult
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (16, 54): Unresolved reference: InlineQueryResultCachedAudio
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (17, 29): Unresolved reference: InlineQueryResultAudio
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (20, 57): Unresolved reference: InlineQueryResultCachedDocument
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (21, 29): Unresolved reference: InlineQueryResultDocument
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (24, 52): Unresolved reference: InlineQueryResultCachedGif
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (25, 29): Unresolved reference: InlineQueryResultGif
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (28, 54): Unresolved reference: InlineQueryResultCachedMpeg4Gif
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (29, 29): Unresolved reference: InlineQueryResultMpeg4Gif
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (32, 54): Unresolved reference: InlineQueryResultCachedPhoto
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (33, 29): Unresolved reference: InlineQueryResultPhoto
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (36, 54): Unresolved reference: InlineQueryResultCachedVideo
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (37, 29): Unresolved reference: InlineQueryResultVideo
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (40, 54): Unresolved reference: InlineQueryResultCachedVoice
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (41, 29): Unresolved reference: InlineQueryResultVideo
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (43, 30): Unresolved reference: InlineQueryResultCachedSticker
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (44, 30): Unresolved reference: InlineQueryResultArticle
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (45, 30): Unresolved reference: InlineQueryResultContact
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (46, 27): Unresolved reference: InlineQueryResultGame
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InlineQueryResultSerializer.kt: (47, 28): Unresolved reference: InlineQueryResultVenue
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (3, 38): Unresolved reference: api
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (10, 38): Unresolved reference: InputMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (10, 59): Unresolved reference: InputMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (12, 88): Unresolved reference: InputMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (16, 21): Unresolved reference: InputContactMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (17, 48): Unresolved reference: InputTextMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (20, 21): Unresolved reference: InputLocationMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/InputMessageContentSerializer.kt: (23, 21): Unresolved reference: InputVenueMessageContent
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (3, 38): Unresolved reference: api
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (9, 65): Unresolved reference: ReplyMarkup
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (9, 78): Unresolved reference: ReplyMarkup
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (10, 88): Unresolved reference: ReplyMarkup
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (12, 52): Unresolved reference: ForceReply
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (13, 56): Unresolved reference: InlineKeyboardMarkup
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (14, 49): Unresolved reference: ReplyKeyboardMarkup
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/ReplyMarkupSerializer.kt: (15, 56): Unresolved reference: ReplyKeyboardRemove
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/TelegramResponse.kt: (3, 38): Unresolved reference: api
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/TelegramResponse.kt: (13, 21): Unresolved reference: ResponseParameters
e: /Users/romain/workspace/sandbox/kotlingram/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/TelegramResponse.kt: (13, 21): Serializer has not been found for type '[ERROR : ResponseParameters]?'. To use context serializer as fallback, explicitly annotate type or property with @Contextual

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:core:compileKotlinJsIr'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
21 actionable tasks: 9 executed, 12 up-to-date
FAIL
```

**Comment by romainbsl** [comment] 2021-02-17 14:25
However, moving from `js(BOTH)` to `js(IR)` brings back the `Unresolved reference: kodein`

**Comment by lamba92** [comment] 2021-02-17 15:37
Somehow using `js(BOTH)` was misconfiguring the task graph and task `:api:core:generateTelegramApi` was not being executed before `:api:core:compilekotlinJsIr`. Fixed with commit [`3c825ea`](https://github.com/lamba92/kotlingram/commit/3c825ea79a04a6ede28d5eed71e743df96237da6).

Now the bug should be reproducible always.

**Comment by SalomonBrys** [comment] 2021-02-23 14:49
Due to a bug in the Kotlin JS IR compiler before 1.4.30, Kodein-DI is not compatible with Kotlin IR compilers before 1.4.30.

In commit 3c825ea, the Kotlin version used by the project is defined by Gradle, rather than by the property set in the gradle.properties file.
The project is therefore compiled with Kotlin 1.4.21, but uses Kotlin-stdlib 1.4.30 (hence the warnings we can see int the build log).

Setting the Kotlin version manually in `buildSrc/build.gradle.kts` to 1.4.30 fixes the issue and allows kotlingram to build correctly.

```
plugins {
    `kotlin-dsl`
    kotlin("jvm") version "1.4.30"
}
```

**Closed by SalomonBrys** 2021-02-23 14:49 UTC
