### ISSUE TITLE
KJS: ClassCastException in runtime when using typed Kodein-modules

### ISSUE THREAD

**Issue by aerialist7** [Kodein-Framework/Kodein-DI#335] opened 2020-10-11 06:18 UTC
#### Problem
* Can't use type-parametrized Kodein-modules since version 7.0.0

#### Details
I'm trying to migrate from Kodein 6.5.5 to 7.0.0 and I'm facing with next error in runtime
```JavaScript
ClassCastException: Illegal cast
    at throwCCE_0 (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/kotlin/1.3.72/kotlin.js?:32670:13)
    at typeToken (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/Kodein-Type-kodein-type/1.1.1/Kodein-Type-kodein-type.js?:370:91)
    at JSKTypeTypeToken.getGenericParameters (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/Kodein-Type-kodein-type/1.1.1/Kodein-Type-kodein-type.js?:303:70)
    at JSKTypeTypeToken.TypeToken.isAssignableFrom_q3o5v9$ (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/Kodein-Type-kodein-type/1.1.1/Kodein-Type-kodein-type.js?:174:35)
    at TypeChecker$Up.check_q3o5v9$ (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/Kodein-DI-kodein-di/7.0.0/Kodein-DI-kodein-di.js?:7121:84)
    at FilteringSequence.eval [as predicate_0] (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/Kodein-DI-kodein-di/7.0.0/Kodein-DI-kodein-di.js?:7284:23)
    at FilteringSequence$iterator$ObjectLiteral.calcNext_0 (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/kotlin/1.3.72/kotlin.js?:41396:41)
    at FilteringSequence$iterator$ObjectLiteral.hasNext (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/kotlin/1.3.72/kotlin.js?:41416:14)
    at FlatteningSequence$iterator$ObjectLiteral.ensureItemIterator_0 (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/kotlin/1.3.72/kotlin.js?:41530:28)
    at FlatteningSequence$iterator$ObjectLiteral.hasNext (webpack:///C:/Projects/Personal/kodein-kotlinjs/build/js/packages_imported/kotlin/1.3.72/kotlin.js?:41523:19)
```

Sample — https://github.com/aerialist7/kodein-kotlinjs/tree/master

#### P.S.
Also I tried to use latest Kotlin and Kodein — https://github.com/aerialist7/kodein-kotlinjs/tree/feature/1.4-7.1
It doesn't works too. I even tried to use `reified` types, but another error occured ([MarkerError](https://youtrack.jetbrains.com/issue/KT-39225))

#### P.P.S.
Working sample on Kodein 6.5.5 — https://github.com/aerialist7/kodein-kotlinjs/tree/feature/1.3-6.5

Related issues:
- https://youtrack.jetbrains.com/issue/KT-42569

**Comment by aerialist7** [comment] 2020-10-26 08:52
Hi! Any news?

**Comment by romainbsl** [comment] 2020-10-29 15:57
Hi. Certainly something has change with our new type system, is it wrong or intended? We are investigating, we'll have some news probably next week.

**Comment by romainbsl** [comment] 2020-11-03 11:30
Hi @aerialist7. Here is a clarification: 

**Kodein-DI 6.5** was using type erasure by default, but that was wrong. In your case the binding looks like:
`{ bind<ComponentFactory>() with ? { ? }=[[object Object]] }`
> Notice that we loose the `T` type here

With **Kodein-DI 7+** we have created a new type system to manage KMP usages. During the process we have decided to 
`{ bind<ComponentFactory<T>>() with ? { ? }=[[object Object]] }`
You cannot bind a generic directly, but you can use a star projection, like:

```kotlin
bind<ComponentFactory<*>>() with singleton {
        SimpleComponentFactory(element)
    }
```

and then retrieving with:
```kotlin
val factory by di.instance<ComponentFactory<*>>()
```

Here is a reproducer https://github.com/romainbsl/kodein-di-issue335

However, if you need to keep the type `T`, you should reify it, but as you mention there is an error, that seems to be a Kotlin compiler issue. Let's hope that it will be fixed quickly.

**Closed by romainbsl** 2020-11-03 11:30 UTC
