### ISSUE TITLE
Gradle dependency issue for Android

### ISSUE THREAD

**Issue by sam43** [Kodein-Framework/Kodein-DI#198] opened 2019-05-08 06:38 UTC
Here is what went wrong:
Could not determine the dependencies of task '`:app:compileDebugRenderscript`'.
> Could not resolve all task dependencies for configuration '`:app:debugCompileClasspath`'.
   > Could not find` org.kodein.di:kodein-di-core-jvm:6.2.0.`
     Required by:
         project :app > `org.kodein.di:kodein-di-generic-jvm:6.2.0`
         project :app >` org.kodein.di:kodein-di-framework-android-core:6.2.0`

N:B: I have read previous issues and possible solutions regarding this but those didn't help out.

Can anyone help please?

**Comment by GabriellCosta** [comment] 2019-05-08 17:52
I think this is the same problem as https://github.com/Kodein-Framework/Kodein-DI/issues/192

**Comment by SalomonBrys** [comment] 2019-05-08 19:54
Duplicate of #192

**Closed by SalomonBrys** 2019-05-08 19:54 UTC
